sonar.projectKey=gerenciador-de-tarefas
sonar.projectName=Gerenciador de Tarefas e Produtividade
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main,frontend/src/app
sonar.tests=backend/src/test,frontend/src/app
sonar.test.inclusions=backend/src/test/**/*.java,frontend/src/app/**/*.test.ts,frontend/src/app/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**,**/*.d.ts
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info