sonar.projectKey=gerenciador-de-tarefas
sonar.projectName=Gerenciador de Tarefas e Produtividade
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**
sonar.tests=backend/src,test